/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Seif
 */
public class CustomerOptions extends javax.swing.JFrame {

    /**
     * Creates new form CustomerOptions
     */
    Customer customer = new Customer();
    public CustomerOptions(Customer c) {
        customer = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShowTripsbtn = new javax.swing.JButton();
        BookAtripbtn = new javax.swing.JButton();
        CancelBookingbtn = new javax.swing.JButton();
        ShowBookingbtn = new javax.swing.JButton();
        UpdateAccountbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ShowTripsbtn.setBackground(new java.awt.Color(0, 0, 0));
        ShowTripsbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ShowTripsbtn.setForeground(new java.awt.Color(255, 255, 255));
        ShowTripsbtn.setText("Show Availiable Trips");
        ShowTripsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTripsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ShowTripsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 230, 53));

        BookAtripbtn.setBackground(new java.awt.Color(0, 0, 0));
        BookAtripbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BookAtripbtn.setForeground(new java.awt.Color(255, 255, 255));
        BookAtripbtn.setText("Book A Trip");
        BookAtripbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookAtripbtnActionPerformed(evt);
            }
        });
        getContentPane().add(BookAtripbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 110, 230, 53));

        CancelBookingbtn.setBackground(new java.awt.Color(0, 0, 0));
        CancelBookingbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CancelBookingbtn.setForeground(new java.awt.Color(255, 255, 255));
        CancelBookingbtn.setText("Cancel Booking");
        CancelBookingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBookingbtnActionPerformed(evt);
            }
        });
        getContentPane().add(CancelBookingbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 180, 230, 53));

        ShowBookingbtn.setBackground(new java.awt.Color(0, 0, 0));
        ShowBookingbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ShowBookingbtn.setForeground(new java.awt.Color(255, 255, 255));
        ShowBookingbtn.setText("Show Booking");
        ShowBookingbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowBookingbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ShowBookingbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 260, 230, 56));

        UpdateAccountbtn.setBackground(new java.awt.Color(0, 0, 0));
        UpdateAccountbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        UpdateAccountbtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateAccountbtn.setText("Update Account");
        UpdateAccountbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAccountbtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateAccountbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(372, 330, 230, 57));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Seif\\Desktop\\blur-city-dark-depth-of-field.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowTripsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTripsbtnActionPerformed

            new ShowTripsTable(customer).setVisible(true);
            this.setVisible(false);    
    }//GEN-LAST:event_ShowTripsbtnActionPerformed

    private void BookAtripbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookAtripbtnActionPerformed
        // TODO add your handling code here:
        new BookTrip(customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BookAtripbtnActionPerformed

    private void CancelBookingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBookingbtnActionPerformed
        new CancelBooking(customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CancelBookingbtnActionPerformed

    private void ShowBookingbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowBookingbtnActionPerformed
        // TODO add your handling code here:
        new ShowBookingTable(customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ShowBookingbtnActionPerformed

    private void UpdateAccountbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAccountbtnActionPerformed
        // TODO add your handling code here:
        new UpdateAccountOptions(customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UpdateAccountbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new CustomerOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookAtripbtn;
    private javax.swing.JButton CancelBookingbtn;
    private javax.swing.JButton ShowBookingbtn;
    private javax.swing.JButton ShowTripsbtn;
    private javax.swing.JButton UpdateAccountbtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
