/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author Seif
 */
public class LogInCustomer extends javax.swing.JFrame {

    /**
     * Creates new form LogInCustomer
     */
    public LogInCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        CustomerEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        CustomerPassword = new javax.swing.JTextField();
        CustomerSigninbtn = new javax.swing.JButton();
        CustomerRegisterbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, 84, 27));
        getContentPane().add(CustomerEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 110, 331, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 90, -1));
        getContentPane().add(CustomerPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 331, -1));

        CustomerSigninbtn.setBackground(new java.awt.Color(0, 0, 0));
        CustomerSigninbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CustomerSigninbtn.setForeground(new java.awt.Color(255, 255, 255));
        CustomerSigninbtn.setText("Sign In");
        CustomerSigninbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerSigninbtnActionPerformed(evt);
            }
        });
        getContentPane().add(CustomerSigninbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 107, 40));

        CustomerRegisterbtn.setBackground(new java.awt.Color(0, 0, 0));
        CustomerRegisterbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CustomerRegisterbtn.setForeground(new java.awt.Color(255, 255, 255));
        CustomerRegisterbtn.setText("Register a new account");
        CustomerRegisterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerRegisterbtnActionPerformed(evt);
            }
        });
        getContentPane().add(CustomerRegisterbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 230, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Seif\\Desktop\\blur-city-dark-depth-of-field.jpg")); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CustomerSigninbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerSigninbtnActionPerformed
        if(this.CustomerEmail.getText().equals("") || this.CustomerPassword.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Fill all blank forms!");
        }
        else
        {
            Customer customer = new Customer();
            String url = "jdbc:sqlserver://SEIFELDEEN:1433;databaseName=TrainSystem;user=sa;password=sa123456;encrypt=false;";        
            try 
            {
                Connection con = DriverManager.getConnection(url);        
                String sql = "SELECT * FROM Customer WHERE Email = ? AND Password = ?";
                PreparedStatement statement = con.prepareStatement(sql);
                statement.setString(1, this.CustomerEmail.getText());
                statement.setString(2, this.CustomerPassword.getText());
                ResultSet result = statement.executeQuery();                                             
                if (result.next()) {
                    JOptionPane.showMessageDialog(this,"LoggedIn Successfully!");
                    String sql1 = "SELECT Customer_id FROM Customer WHERE Email = ? AND Password = ?";
                    PreparedStatement statement1 = con.prepareStatement(sql1);
                    statement1.setString(1, this.CustomerEmail.getText());
                    statement1.setString(2, this.CustomerPassword.getText());
                    ResultSet result1 = statement1.executeQuery();                
                    if (result1.next())
                    {
                        customer.Customer_id = result1.getInt("Customer_id");
                        new CustomerOptions(customer).setVisible(true);
                        this.setVisible(false);                        
                    }
                        
                } 
                else 
                {                    
                    JOptionPane.showMessageDialog(this,"Login Failed , Invalid Email or Password");                       
                }                             
            }

            catch (SQLException e) {
                System.out.println("Error connecting to database: " + e.getMessage());        
            }
        }        
        
    }//GEN-LAST:event_CustomerSigninbtnActionPerformed

    private void CustomerRegisterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerRegisterbtnActionPerformed
        // TODO add your handling code here:
        new RegisterCustomer().setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_CustomerRegisterbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new LogInCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustomerEmail;
    private javax.swing.JTextField CustomerPassword;
    private javax.swing.JButton CustomerRegisterbtn;
    private javax.swing.JButton CustomerSigninbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
