/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Scanner;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;

/**
 *
 * @author Seif
 */
public class RegisterCustomer extends javax.swing.JFrame {

    /**
     * Creates new form RegisterCustomer
     */
    public RegisterCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        RegisterCustomerbtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Password = new javax.swing.JTextField();
        ConfirmPassword = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        PhoneNumber = new javax.swing.JTextField();
        BirthYear = new javax.swing.JTextField();
        BirthMonth = new javax.swing.JTextField();
        BirthDay = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 120, 38));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Last Name");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 110, 34));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Email");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 90, 29));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 90, 29));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Confirm Password");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, -1, 32));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 95, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone Number");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, 130, 36));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Birth Day");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 470, 95, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Birth Month");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 410, 100, 34));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Birth Year");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 85, 28));

        RegisterCustomerbtn.setBackground(new java.awt.Color(0, 0, 0));
        RegisterCustomerbtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RegisterCustomerbtn.setForeground(new java.awt.Color(255, 255, 255));
        RegisterCustomerbtn.setText("Register");
        RegisterCustomerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterCustomerbtnActionPerformed(evt);
            }
        });
        getContentPane().add(RegisterCustomerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 507, 169, 40));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 507, 159, 40));
        getContentPane().add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 438, -1));
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 87, 438, -1));
        getContentPane().add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 136, 438, -1));
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 183, 438, -1));

        ConfirmPassword.setToolTipText("");
        getContentPane().add(ConfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 232, 438, -1));
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 277, 438, -1));
        getContentPane().add(PhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 325, 438, -1));
        getContentPane().add(BirthYear, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 367, 438, -1));
        getContentPane().add(BirthMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 419, 438, -1));
        getContentPane().add(BirthDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(268, 469, 438, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\Seif\\Desktop\\blur-city-dark-depth-of-field.jpg")); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterCustomerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterCustomerbtnActionPerformed
        if(this.FirstName.getText().equals("")||this.LastName.getText().equals("")||this.Email.getText().equals("")
                ||this.Password.getText().equals("")||this.Address.getText().equals("")||this.PhoneNumber.getText().equals("")
                ||this.BirthYear.getText().equals("")||this.BirthMonth.getText().equals("")||this.BirthDay.getText().equals("")
                ||this.ConfirmPassword.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Fill all blank forms!");
        }
        else
        {
            Customer customer = new Customer();                        
            //------------------------------------------------        
            customer.Fname = this.FirstName.getText();
            //-----------------------------------------------------
            customer.Lname = this.LastName.getText();
            //-----------------------------------------------------
            customer.Email = this.Email.getText();         
            Pattern regexPattern = Pattern.compile("^\\w+([.-]?\\w+)@\\w+([.-]?\\w+)(.\\w{2,3})+$");
            Matcher m1 = regexPattern.matcher(customer.Email);                
            //-----------------------------------------------------
            customer.Password = this.Password.getText(); 
            regexPattern = Pattern.compile("^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%^&+=!])(?=\\S+$).{8,15}$");
            Matcher m2 = regexPattern.matcher(customer.Password);                                
            //-----------------------------------------------------
            customer.Address = this.Address.getText(); 
            //-----------------------------------------------------
            customer.PhoneNo = this.PhoneNumber.getText(); 
            //----------------------------------------------------- 
            customer.BirthYear = Integer.parseInt(this.BirthYear.getText()); 
            //-----------------------------------------------------  
            customer.BirthMonth = Integer.parseInt(this.BirthMonth.getText()); 
            //-----------------------------------------------------
            customer.BirthDay = Integer.parseInt(this.BirthDay.getText()); 
            //-----------------------------------------------------  
            if(!m1.matches())
            {
                JOptionPane.showMessageDialog(this,"Invalid Email, Enter a valid one");
            }
            else if (!m2.matches())
            {
                JOptionPane.showMessageDialog(this,"Invalid Password, Enter a valid one");
            }
            else if(!this.ConfirmPassword.getText().equals(customer.Password))
            {
                JOptionPane.showMessageDialog(this,"The confirm Password doesn't match, Try again");
            }
            else
            {            
                String url = "jdbc:sqlserver://SEIFELDEEN:1433;databaseName=TrainSystem;user=sa;password=sa123456;encrypt=false;";
                try {
                    Connection con = DriverManager.getConnection(url);            
                    String sql = "INSERT INTO Customer (Fname, Lname, Email,Password, Address, PhoneNo, BirthYear, BirthMonth, BirthDay) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";             
                    PreparedStatement statement = con.prepareStatement(sql);
                    statement.setString(1, customer.Fname);
                    statement.setString(2, customer.Lname);
                    statement.setString(3, customer.Email);
                    statement.setString(4, customer.Password);
                    statement.setString(5, customer.Address);  
                    statement.setString(6, customer.PhoneNo);
                    statement.setInt(7, customer.BirthYear);
                    statement.setInt(8, customer.BirthMonth);
                    statement.setInt(9, customer.BirthDay);
                    int rowsInserted = statement.executeUpdate();
                    if (rowsInserted > 0) 
                    {
                        JOptionPane.showMessageDialog(this,"Registeration Completed!");
                        new LogInCustomer().setVisible(true);
                        this.setVisible(false);
                    } 
                    else 
                    {
                        JOptionPane.showMessageDialog(this,"Registeration Failed!");                    
                    }
                } 
                catch (SQLException e) 
                {
                    System.out.println("Error connecting to database: " + e.getMessage());                
                }
            }
        }        
    //-------------------------------------------------------------------------------------------------------------------
    }//GEN-LAST:event_RegisterCustomerbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new LogInCustomer().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField BirthDay;
    private javax.swing.JTextField BirthMonth;
    private javax.swing.JTextField BirthYear;
    private javax.swing.JTextField ConfirmPassword;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField Password;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JButton RegisterCustomerbtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
