/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Seif
 */
public class ShowTripsTable extends javax.swing.JFrame {

    /**
     * Creates new form ShowTripsTable
     */
    Customer customer = new Customer();
    public ShowTripsTable(Customer c) {
        customer = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ShowTripsbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ShowTripsbtn.setBackground(new java.awt.Color(0, 0, 0));
        ShowTripsbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ShowTripsbtn.setForeground(new java.awt.Color(255, 255, 255));
        ShowTripsbtn.setText("Show");
        ShowTripsbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTripsbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ShowTripsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 153, 55));

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Trip ID", "Price", "Trip Time", "Source", "Destination", "Date", "Avaliable Seats"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 662, -1));

        Backbtn.setBackground(new java.awt.Color(0, 0, 0));
        Backbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Backbtn.setForeground(new java.awt.Color(255, 255, 255));
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, 140, 55));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Seif\\Desktop\\blur-city-dark-depth-of-field.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ShowTripsbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTripsbtnActionPerformed
        // TODO add your handling code here:        
        String url = "jdbc:sqlserver://SEIFELDEEN:1433;databaseName=TrainSystem;user=sa;password=sa123456;encrypt=false;";        
        try (Connection con = DriverManager.getConnection(url)) {
            String sql = "SELECT * FROM Trip";
            PreparedStatement statement = con.prepareStatement(sql);
            ResultSet result = statement.executeQuery();            

            while (result.next())
            {
                String sql1 = "SELECT Train_Seats FROM Train WHERE Train_ID = ?";
                PreparedStatement statement1 = con.prepareStatement(sql1);
                statement1.setInt(1, result.getInt("trainID"));
                ResultSet result1 = statement1.executeQuery();                
                result1.next();
                
                String TripID = String.valueOf(result.getInt("Trip_ID"));
                String Price = String.valueOf(result.getFloat("Price"));
                String TripTime = String.valueOf(result.getString("Trip_Time"));
                String Source = String.valueOf(result.getString("Source"));
                String Destination = String.valueOf(result.getString("Destination"));
                String Date = String.valueOf(Integer.toString(result.getInt("Trip_Day")) +"/"+ Integer.toString(result.getInt("Trip_Month"))+"/" + Integer.toString(result.getInt("Trip_Year")));
                String Seats = String.valueOf(result1.getInt("Train_Seats"));
                
                String tbData[] = {TripID,Price,TripTime,Source,Destination,Date,Seats};
                DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
                //tb1Model.setRowCount(0);
                tb1Model.addRow(tbData);                
            }
            ShowTripsbtn.setEnabled(false);            
        } catch (SQLException e) {
            System.out.println("Error connecting to database: " + e.getMessage());
        }
    }//GEN-LAST:event_ShowTripsbtnActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        new CustomerOptions(customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowTripsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowTripsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowTripsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowTripsTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new ShowTripsTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton ShowTripsbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
