/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Seif
 */
public class SystemReport extends javax.swing.JFrame {

    /**
     * Creates new form SystemReport
     */
    Admin admin = new Admin();
    public SystemReport(Admin a) {
        admin = a;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ShowReportbtn = new javax.swing.JButton();
        Cancelbtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Seif\\Desktop\\blur-city-dark-depth-of-field.jpg")); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(255, 255, 255));
        jTable1.setForeground(new java.awt.Color(0, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customers' Count", "Admins' Count", "Trips' Count", "Trains' Count"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Customers' Count");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Admins' Count");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Trips' Count");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Trains' Count");
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 530, 50));

        ShowReportbtn.setBackground(new java.awt.Color(0, 0, 0));
        ShowReportbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ShowReportbtn.setForeground(new java.awt.Color(255, 255, 255));
        ShowReportbtn.setText("Show");
        ShowReportbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowReportbtnActionPerformed(evt);
            }
        });
        getContentPane().add(ShowReportbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 180, 50));

        Cancelbtn.setBackground(new java.awt.Color(0, 0, 0));
        Cancelbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Cancelbtn.setForeground(new java.awt.Color(255, 255, 255));
        Cancelbtn.setText("Cancel");
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 180, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Seif\\Desktop\\blur-city-dark-depth-of-field.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        // TODO add your handling code here:
        new AdminOptionsPage(admin).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CancelbtnActionPerformed

    private void ShowReportbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowReportbtnActionPerformed
        // TODO add your handling code here:
        String url = "jdbc:sqlserver://SEIFELDEEN:1433;databaseName=TrainSystem;user=sa;password=sa123456;encrypt=false;"; 
        int Customercount = 0;
        int Admincount = 0;
        int Tripscount = 0;
        int Trainscount = 0;        
        try {
            Connection con = DriverManager.getConnection(url);
            String sql = "SELECT count(Customer_id) AS Number FROM Customer";
            PreparedStatement statement = con.prepareStatement(sql);
            ResultSet result = statement.executeQuery();

            while(result.next())
            {
                Customercount = result.getInt("Number");                                            
            }
                        
        } catch (SQLException e) {
            System.out.println("Error connecting to database: " + e.getMessage());
        }
        //--------------------------------------------------------------------------------------
        try {
            Connection con = DriverManager.getConnection(url);
            String sql = "SELECT count(admin_id) AS Number FROM Admin";
            PreparedStatement statement = con.prepareStatement(sql);
            ResultSet result = statement.executeQuery();            

            if (result.next())
            {
                Admincount = result.getInt("Number");                                            
            }
                        
        } catch (SQLException e) {
            System.out.println("Error connecting to database: " + e.getMessage());
        }
        //--------------------------------------------------------------------------------------
        try {
            Connection con = DriverManager.getConnection(url);
            String sql = "SELECT count(Trip_ID) AS Number FROM Trip";
            PreparedStatement statement = con.prepareStatement(sql);
            ResultSet result = statement.executeQuery();            

            if (result.next())
            {
                Tripscount = result.getInt("Number");                                            
            }
                        
        } catch (SQLException e) {
            System.out.println("Error connecting to database: " + e.getMessage());
        }
        //--------------------------------------------------------------------------------------
        try{
            Connection con = DriverManager.getConnection(url);
            String sql = "SELECT count(Train_Name) AS Number FROM Train";
            PreparedStatement statement = con.prepareStatement(sql);
            ResultSet result = statement.executeQuery();            

            if (result.next())
            {
                Trainscount = result.getInt("Number");                                            
            }
                        
        } catch (SQLException e) {
            System.out.println("Error connecting to database: " + e.getMessage());
        }
        //------------------------------------------------------------
        String tbData[] = {Integer.toString(Customercount),Integer.toString(Admincount),Integer.toString(Tripscount),Integer.toString(Trainscount)};
        DefaultTableModel tb1Model = (DefaultTableModel)jTable1.getModel();
        tb1Model.addRow(tbData);
        ShowReportbtn.setEnabled(false);
    }//GEN-LAST:event_ShowReportbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new SystemReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JButton ShowReportbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
