/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Seif
 */
public class UpdateCustomerAddress extends javax.swing.JFrame {

    /**
     * Creates new form UpdateCustomerAddress
     */
    Customer customer = new Customer();
    public UpdateCustomerAddress(Customer c) {
        customer = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        NewAddress = new javax.swing.JTextField();
        UpdateAddressbtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("New Address:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 159, 53));

        NewAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewAddressActionPerformed(evt);
            }
        });
        getContentPane().add(NewAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 163, 559, 30));

        UpdateAddressbtn.setBackground(new java.awt.Color(0, 0, 0));
        UpdateAddressbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdateAddressbtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateAddressbtn.setText("Update");
        UpdateAddressbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAddressbtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateAddressbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 167, 53));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, 178, 53));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Seif\\Desktop\\blur-city-dark-depth-of-field.jpg")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new UpdateAccountOptions(customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void NewAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewAddressActionPerformed

    private void UpdateAddressbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAddressbtnActionPerformed
        // TODO add your handling code here:
        if(this.NewAddress.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Fill all blank forms!");
        }
        else
        {
            String url = "jdbc:sqlserver://SEIFELDEEN:1433;databaseName=TrainSystem;user=sa;password=sa123456;encrypt=false;";        
            try 
            {
                Connection con = DriverManager.getConnection(url);        
                String sql = "Update Customer\n" +
                             "  Set Address = ? \n" +
                             "  Where Customer_id = ?";
                PreparedStatement statement = con.prepareStatement(sql);
                statement.setString(1, this.NewAddress.getText());  
                statement.setInt(2, customer.Customer_id);  
                int rowsInserted1 = statement.executeUpdate();
                if (rowsInserted1 > 0)
                {
                    JOptionPane.showMessageDialog(this,"Address Updated Successfully!");
                    new UpdateAccountOptions(customer).setVisible(true);
                    this.setVisible(false);
                }                
                else 
                {                    
                    JOptionPane.showMessageDialog(this,"Customer Not Found!");
                }                             
            }            
            catch (SQLException e) {
                System.out.println("Error connecting to database: " + e.getMessage());        
            }
        }        
    }//GEN-LAST:event_UpdateAddressbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomerAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomerAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomerAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateCustomerAddress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new UpdateCustomerAddress().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField NewAddress;
    private javax.swing.JButton UpdateAddressbtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
