/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainsystem;

/**
 *
 * @author Seif
 */
public class UpdateAccountOptions extends javax.swing.JFrame {

    /**
     * Creates new form UpdateAccountOptions
     */
    Customer customer = new Customer();
    public UpdateAccountOptions(Customer c) {
        customer = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UpdatePassbtn = new javax.swing.JButton();
        UpdateAddressbtn = new javax.swing.JButton();
        UpdatePhonebtn = new javax.swing.JButton();
        Backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UpdatePassbtn.setBackground(new java.awt.Color(0, 0, 0));
        UpdatePassbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdatePassbtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdatePassbtn.setText("Update Password");
        UpdatePassbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePassbtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdatePassbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 70, 230, 66));

        UpdateAddressbtn.setBackground(new java.awt.Color(0, 0, 0));
        UpdateAddressbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdateAddressbtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdateAddressbtn.setText("Update Address");
        UpdateAddressbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateAddressbtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdateAddressbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 180, 230, 67));

        UpdatePhonebtn.setBackground(new java.awt.Color(0, 0, 0));
        UpdatePhonebtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdatePhonebtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdatePhonebtn.setText("Update Phone Number");
        UpdatePhonebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePhonebtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdatePhonebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 230, 67));

        Backbtn.setBackground(new java.awt.Color(0, 0, 0));
        Backbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Backbtn.setForeground(new java.awt.Color(255, 255, 255));
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(368, 400, 230, 67));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Seif\\Desktop\\blur-city-dark-depth-of-field.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        new CustomerOptions(customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackbtnActionPerformed

    private void UpdatePassbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePassbtnActionPerformed
        // TODO add your handling code here:
        new UpdatePassword(customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UpdatePassbtnActionPerformed

    private void UpdateAddressbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateAddressbtnActionPerformed
        // TODO add your handling code here:
        new UpdateCustomerAddress(customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UpdateAddressbtnActionPerformed

    private void UpdatePhonebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePhonebtnActionPerformed
        // TODO add your handling code here:
        new UpdateCustomerPhone(customer).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UpdatePhonebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateAccountOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateAccountOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateAccountOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateAccountOptions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new UpdateAccountOptions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JButton UpdateAddressbtn;
    private javax.swing.JButton UpdatePassbtn;
    private javax.swing.JButton UpdatePhonebtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
