/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trainsystem;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Seif
 */
public class UpdatePassword extends javax.swing.JFrame {

    /**
     * Creates new form UpdatePassword
     */
     Customer customer = new Customer();
    public UpdatePassword(Customer c) {
        customer = c;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Oldpass = new javax.swing.JTextField();
        Newpass = new javax.swing.JTextField();
        CNewpass = new javax.swing.JTextField();
        UpdatePassbtn = new javax.swing.JButton();
        Cancelbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Old Password");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 180, 43));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("New Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 196, 47));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm New Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 210, 50));
        getContentPane().add(Oldpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 103, 520, 30));
        getContentPane().add(Newpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 197, 517, 30));
        getContentPane().add(CNewpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 515, 30));

        UpdatePassbtn.setBackground(new java.awt.Color(0, 0, 0));
        UpdatePassbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        UpdatePassbtn.setForeground(new java.awt.Color(255, 255, 255));
        UpdatePassbtn.setText("Update");
        UpdatePassbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatePassbtnActionPerformed(evt);
            }
        });
        getContentPane().add(UpdatePassbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 186, 49));

        Cancelbtn.setBackground(new java.awt.Color(0, 0, 0));
        Cancelbtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Cancelbtn.setForeground(new java.awt.Color(255, 255, 255));
        Cancelbtn.setText("Cancel");
        Cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Cancelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 186, 49));

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Seif\\Desktop\\blur-city-dark-depth-of-field.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelbtnActionPerformed
        // TODO add your handling code here:
        new UpdateAccountOptions(customer).setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_CancelbtnActionPerformed

    private void UpdatePassbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatePassbtnActionPerformed
        // TODO add your handling code here:
        if(this.Oldpass.getText().equals("")||this.Newpass.getText().equals("")||this.CNewpass.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Fill all blank forms!");
        }
        else if(!(this.Newpass.getText().equals(this.CNewpass.getText())))
        {
            JOptionPane.showMessageDialog(this,"Confirm password doesn't match new password!");
        }
        else
        {
            String url = "jdbc:sqlserver://SEIFELDEEN:1433;databaseName=TrainSystem;user=sa;password=sa123456;encrypt=false;";        
            try 
            {
                Connection con = DriverManager.getConnection(url);        
                String sql = "SELECT Password FROM Customer WHERE Customer_id = ?";
                PreparedStatement statement = con.prepareStatement(sql);
                statement.setInt(1, customer.Customer_id);            
                ResultSet result = statement.executeQuery();                                             
                if (result.next()) {
                    if(this.Oldpass.getText().equals(result.getString("Password")))
                    {                    
                        String sql1 = "Update Customer\n" +
                                  "SET Password = ?\n" +
                                  "WHERE Customer_id = ?";  
                        PreparedStatement statement1 = con.prepareStatement(sql1);
                        statement1.setString(1, this.Newpass.getText());
                        statement1.setInt(2, customer.Customer_id);
                        int rowsInserted1 = statement1.executeUpdate();
                        if (rowsInserted1 > 0)
                        {
                            JOptionPane.showMessageDialog(this,"Password Updated Successfully!");
                            new UpdateAccountOptions(customer).setVisible(true);
                            this.setVisible(false);
                        }                            
                    }
                    else
                        JOptionPane.showMessageDialog(this,"The Old Password is Wrong");
                } 
                else 
                {                    
                    JOptionPane.showMessageDialog(this,"Customer Not Found!");                        
                }                             
            }            
            catch (SQLException e) 
            {
                System.out.println("Error connecting to database: " + e.getMessage());        
            }
        }        
    }//GEN-LAST:event_UpdatePassbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdatePassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new UpdatePassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CNewpass;
    private javax.swing.JButton Cancelbtn;
    private javax.swing.JTextField Newpass;
    private javax.swing.JTextField Oldpass;
    private javax.swing.JButton UpdatePassbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
